dist: xenial
language: scala
jdk:
- openjdk11
scala:
- 2.12.8
before_install:
- sudo apt-get update
- sudo apt-get install -y libxcb-shape0 libxcb-shape0-dev libxcb-xfixes0 libxcb-xfixes0-dev
- sudo snap install snapcraft --classic
env:
  - SNAPCRAFT_BUILD_ENVIRONMENT=host
script:
- snapcraft
sudo: required
deploy:
  'on':
    branch: master
  provider: snap
  snap: rust-keylock-ui*.snap
  channel: edge
  skip_cleanup: true
