dist: xenial
language: scala
rust:
  - stable
jdk:
  - openjdk11
scala:
  - 2.12.8
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
script:
  - mvn -f scala/pom.xml clean install
  - cargo build --manifest-path=rust/Cargo.toml
