dist: bionic
language: java
sudo: required

addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic
    - name: lxd
      channel: stable

rust:
  - stable

jdk:
  - openjdk13

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxcb-shape0 libxcb-shape0-dev libxcb-xfixes0 libxcb-xfixes0-dev
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
  - sudo snap install snapcraft --classic

script:
  - mvn -f java/pom.xml clean install
  - cargo build --manifest-path=rust/Cargo.toml
#  - echo "Starting migration"
#  - sudo /snap/bin/lxd.migrate -yes
#  - echo "Waiting to get ready"
#  - sudo /snap/bin/lxd waitready
#  - echo "Initializing"
#  - sudo /snap/bin/lxd init --auto
#  - echo "Executing snapcraft"
  - sudo snapcraft --use-lxd

after_failure:
  - sudo journalctl -u snapd

deploy:
  'on':
    branch: master
  provider: snap
  snap: rust-keylock-ui*.snap
  channel: edge
  skip_cleanup: true
