dist: xenial
language: scala
rust:
  - stable
jdk:
  - openjdk11
scala:
  - 2.12.8
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxcb-shape0 libxcb-shape0-dev libxcb-xfixes0 libxcb-xfixes0-dev
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
sudo: required
script:
  - mvn -f scala/pom.xml clean install
  - cargo build --manifest-path=rust/Cargo.toml
