dist: xenial
language: scala
services: docker
rust:
- stable
jdk:
- openjdk11
scala:
- 2.12.8
before_install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- source ~/.cargo/env
script:
- mvn -f scala/pom.xml clean install
- cargo build --manifest-path=rust/Cargo.toml
sudo: required
deploy:
  'on':
    branch: master
  provider: snap
  snap: rust-keylock-ui
  channel: edge
  skip_cleanup: true
