dist: xenial
language: scala
jdk:
- openjdk11
scala:
- 2.12.8
before_install:
before_install:
- sudo apt-get update
- sudo apt-get install -y libxcb-shape0 libxcb-shape0-dev libxcb-xfixes0 libxcb-xfixes0-dev
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- source ~/.cargo/env
script:
- mvn -f scala/pom.xml clean install
- cargo build --manifest-path=rust/Cargo.toml
sudo: required
deploy:
  'on':
    branch: master
  provider: snap
  snap: rust-keylock-ui
  channel: edge
  skip_cleanup: true
