dist: trusty

language: scala
services: docker

rust:
  - stable

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
scala:
   - 2.12.4

before_install:
   - curl https://sh.rustup.rs -sSf | sh -s -- -y
   - source ~/.cargo/env
   - sh build-scripts/build_rust_for_rust_keylock_ui.sh

script:
   - mvn -f scala/pom.xml clean install