dist: xenial
language: java
rust:
  - stable
jdk:
  - openjdk11
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxcb-shape0 libxcb-shape0-dev libxcb-xfixes0 libxcb-xfixes0-dev
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
  - sudo snap install snapcraft --classic
sudo: required
script:
  - mvn -f java/pom.xml clean install
  - cargo build --manifest-path=rust/Cargo.toml
  - snapcraft
deploy:
  'on':
    branch: master
  provider: snap
  snap: rust-keylock-ui*.snap
  channel: edge
  skip_cleanup: true
