[package]
name = "rust-keylock-ui-rust"
version = "0.7.0"
authors = ["aston <astonbitecode@gmail.com>"]
edition = "2015"

[[bin]]
name = "rust-keylock-ui"
path = "src/main.rs"

[dependencies]
rust_keylock = {git = "https://github.com/rust-keylock/rust-keylock-lib"}
j4rs = {git = "https://github.com/astonbitecode/j4rs"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
log4rs = "0.8"
dirs = "1.0"

[build-dependencies]
fs_extra = "1.1.0"