[package]
name = "rust-keylock-ui-rust"
version = "0.5.0"
authors = ["aston <astonbitecode@gmail.com>"]

[[bin]]
name = "rust-keylock-ui"
path = "src/main.rs"

[dependencies]
rust_keylock = {git = "https://github.com/rust-keylock/rust-keylock-lib.git"}
lazy_static = "0.2"
j4rs = {git = "https://github.com/astonbitecode/j4rs.git", rev = "dc4a95f48a96fd0ba3fe0c0addb24ed9ab598ff2"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
log4rs = "0.8"

[build-dependencies]
fs_extra = "1.1.0"