[package]
name = "rust-keylock-ui-rust"
version = "0.8.1"
authors = ["aston <astonbitecode@gmail.com>"]
edition = "2018"

[[bin]]
name = "rust-keylock-ui-app"
path = "src/main.rs"

[[bin]]
name = "rust-keylock-ui"
path = "runner/src/main.rs"

[dependencies]
rust_keylock = "0.8"
j4rs = {git = "https://github.com/astonbitecode/j4rs", rev = "b444270e44142218adf45b9824856f74ab8533c8"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
log4rs = "0.8"
dirs = "1.0"
glob = "0.2"

[build-dependencies]
fs_extra = "1.1.0"