[package]
name = "rust-keylock-ui-rust"
version = "0.4.0"
authors = ["aston <astonbitecode@gmail.com>"]

[[bin]]
name = "rust-keylock-ui"
path = "src/main.rs"

[dependencies]
rust_keylock = "0.4"
lazy_static = "0.2"
j4rs = {git = "https://github.com/astonbitecode/j4rs.git"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
log4rs = "0.8"

[build-dependencies]
fs_extra = "1.1.0"