[package]
name = "rust-keylock-ui-rust"
version = "0.3.0"
authors = ["aston <astonbitecode@gmail.com>"]

[lib]
name = "rustkeylockui"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
rust_keylock = { path = "../../rust-keylock-lib" }
libc = "0.2"
lazy_static = "0.2"
log = "0.3"
