name: rust-keylock-ui
version: '0.8.1'
summary: A password manager written (mostly) in Rust
description: |
 rust-keylock is a password manager and its goals are to be:
    - Secure
    - Simple to use
    - Portable
    - Extensible
 The core logic is written in Rust, but the presentation/User interaction parts are in different languages.
 rust-keylock-ui manages the rust-keylock core, providing a User Interface using JavaFX (via ScalaFX).

grade: devel
confinement: strict
icon: snap/gui/rkl.png

parts:
  rust-keylock-ui-all:
    plugin: maven
    source: https://github.com/rust-keylock/rust-keylock-ui.git
#    source-tag: v0.8.1
    override-build: |
      # Build Scala
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}"
      mvn -f ./scala clean install
      # Setup Rust
      BASEDIR=`pwd`
      mkdir -p $BASEDIR/tools/.cargo
      mkdir -p $BASEDIR/tools/.rustup
      export CARGO_HOME=$BASEDIR/tools/.cargo
      RUSTUP_HOME=$BASEDIR/tools/.rustup
      PATH=$CARGO_HOME/bin:$PATH
      curl https://sh.rustup.rs -sSf > $BASEDIR/tools/rustup.sh
      chmod +x $BASEDIR/tools/rustup.sh
      CARGO_HOME=$BASEDIR/tools/.cargo RUSTUP_HOME=$BASEDIR/tools/.rustup sh tools/rustup.sh --no-modify-path -y
      $CARGO_HOME/bin/rustup default stable
      # Build j4rs
      echo Building the j4rs library
      cd $BASEDIR/tools
      git clone https://github.com/astonbitecode/j4rs.git
      $CARGO_HOME/bin/cargo build --manifest-path=j4rs/rust/Cargo.toml --release
      # Build rust-keylock-ui-rust
      echo Building rust-keylock-ui-rust
      cd $BASEDIR
      $CARGO_HOME/bin/cargo build --manifest-path=rust/Cargo.toml --release
    build-packages:
      - openjdk-8-jdk
      - openjfx
      - openssl
      - libssl-dev
      - git
      - libxcb-shape0
      - libxcb-shape0-dev
      - libxcb-xfixes0
      - libxcb-xfixes0-dev
    stage-packages:
      - openjdk-8-jdk
      - openjfx
      - openssl
      - libssl1.0.0
      - libxcb-shape0
      - libxcb-xfixes0
    organize:
      ../build/scala/target/desktop-ui-0.8.1.jar: bin/scalaassets/desktop-ui-0.8.1.jar
      ../build/scala/target/lib/: bin/scalaassets/lib/
      ../build/rust/target/release/jassets: bin/jassets
      ../build/rust/target/release/rust-keylock-ui: bin/
      ../build/tools/j4rs/rust/target/release/libj4rs.so: bin/deps/libj4rs.so
  env:
    plugin: nil
    after:
      - rust-keylock-ui-all
      - desktop-glib-only
apps:
  rust-keylock-ui:
    command: desktop-launch $SNAP/bin/rust-keylock-ui
    plugs:
      - x11
      - opengl
      - network
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}/jre/lib/${SNAP_ARCH}/server:${SNAP}/usr/local/lib:${SNAP}/tools/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:$LD_LIBRARY_PATH