name: rust-keylock-ui
version: '0.7.0'
summary: A password manager written (mostly) in Rust
description: |
 rust-keylock is a password manager and its goals are to be:
    - Secure
    - Simple to use
    - Portable
    - Extensible
 The core logic is written in Rust, but the presentation/User interaction parts are in different languages.
 rust-keylock-ui manages the rust-keylock core, providing a User Interface using JavaFX (via ScalaFX).

grade: devel
confinement: strict
icon: snap/gui/rkl.png

parts:
  rust-keylock-ui-scala:
    plugin: maven
    source: https://github.com/rust-keylock/rust-keylock-ui.git
#    source-tag: v0.7.0
    override-build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}"
      mvn -f ./scala clean install
    build-packages:
      - openjdk-8-jdk
      - openjfx
    stage-packages:
      - openjdk-8-jdk
      - openjfx
    organize:
      ../build/scala/target/desktop-ui-0.7.0.jar: bin/scalaassets/desktop-ui-0.7.0.jar
      ../build/scala/target/lib/: bin/scalaassets/lib/

  rust-keylock-ui-rust:
    source: https://github.com/rust-keylock/rust-keylock-ui.git
    source-subdir: rust/
#    source-tag: v0.7.0
    after:
      - rust-keylock-ui-scala
    plugin: rust
    rust-revision: 1.29.2
    build-packages:
      - openssl
      - libssl-dev
    stage-packages:
      - openssl
      - libssl1.0.0
    organize:
      ../build/rust/target/release/jassets: bin/jassets
      ../build/rust/target/release/deps/libj4rs-*.so: bin/deps/
  env:
    plugin: nil
    after:
      - rust-keylock-ui-rust
      - desktop-glib-only
apps:
  rust-keylock-ui:
    command: desktop-launch $SNAP/bin/rust-keylock-ui
    plugs:
      - x11
      - opengl
      - network
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}/jre/lib/${SNAP_ARCH}/server:${SNAP}/usr/local/lib:$LD_LIBRARY_PATH